logging:
    level:
      root: INFO
      '[org.springframework.web]': INFO
      '[org.springframework.web.filter.CommonsRequestLoggingFilter]': DEBUG
    file:
      path: logs
    logback: 
      rollingpolicy: 
        max-history: 10
        max-file-size: 100MB
        total-size-cap: 1GB
#Graceful shutdown
server:
  shutdown: graceful
spring: 
  main:
    allow-circular-references: true 
  lifecycle: 
    timeout-per-shutdown-phase: 30s